"""job match score columns

Revision ID: 6b4336791fe0
Revises: 4d8cdacaf828
Create Date: 2026-08-26 07:53:58.711425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b4336791fe0'
down_revision: Union[str, None] = '4d8cdacaf828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('match_score', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('match_reasons', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('job', sa.Column('match_part_time_fit', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('match_scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'match_scored_at')
    op.drop_column('job', 'match_part_time_fit')
    op.drop_column('job', 'match_reasons')
    op.drop_column('job', 'match_score')
    # ### end Alembic commands ###
