"""ai_run cost logging

Revision ID: 88e8d0183de7
Revises: 6c122cdd3e60
Create Date: 2026-08-26 07:11:49.365416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e8d0183de7'
down_revision: Union[str, None] = '6c122cdd3e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_run_created_at'), 'ai_run', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_run_feature'), 'ai_run', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_run_job_id'), 'ai_run', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_run_job_id'), table_name='ai_run')
    op.drop_index(op.f('ix_ai_run_feature'), table_name='ai_run')
    op.drop_index(op.f('ix_ai_run_created_at'), table_name='ai_run')
    op.drop_table('ai_run')
    # ### end Alembic commands ###
