name: Bug
description: Report a bug
labels: ["type:bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happens
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: expected
    attributes:
      label: Expected
